services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TZ: "Asia/Singapore"  # Set the time zone for the application
    depends_on:
      - db
      - redis
    networks:
      - webflux-demo-network

  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Singapore"  # Set the time zone for the database
    ports:
      - "5432:5432"
    networks:
      - webflux-demo-network
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    networks:
      - webflux-demo-network

networks:
  webflux-demo-network:
    driver: bridge