services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: meirongdev/webflux-app:latest
    ports:
      - "9010:9010"
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TZ: "Asia/Singapore"  # Set the time zone for the application
    depends_on:
      - db
      - redis
    networks:
      - webflux-demo-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 4G

  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Singapore"  # Set the time zone for the database
    ports:
      - "5432:5432"
    networks:
      - webflux-demo-network
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    networks:
      - webflux-demo-network

  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webflux-demo-network

  grafana:
    image: grafana/grafana:11.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - webflux-demo-network

networks:
  webflux-demo-network:
    driver: bridge