server:
  port: 8080
spring:
  config:
    activate:
      on-profile: default
  application:
    name: webflux-app
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: postgres
    properties:
      schema: myschema
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:postgresql://db:5432/mydatabase
    username: postgres
    password: postgres
    properties:
      schema: myschema
  data:
    redis:
      host: redis
      port: 6379
  
    
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:tc:postgresql:///testdb?TC_IMAGE_TAG=17-alpine
---